package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// knownAgent describes a CLI AI agent that should be auto-proxied.
type knownAgent struct {
	Binary string
	Name   string
}

// knownAgents is the list of AI agent CLIs to detect and wrap.
var knownAgents = []knownAgent{
	{"claude", "Claude Code"},
	{"codex", "Codex"},
	{"aider", "Aider"},
	{"copilot", "GitHub Copilot CLI"},
	{"opencode", "OpenCode"},
	{"pi", "Pi Coding Agent"},
	{"cline", "Cline"},
	{"continue", "Continue"},
	{"goose", "Goose"},
	{"sweep", "Sweep"},
	{"mentat", "Mentat"},
	{"gpt-engineer", "GPT Engineer"},
	{"smol-developer", "Smol Developer"},
	{"devin", "Devin CLI"},
	{"bolt", "Bolt"},
	{"lovable", "Lovable CLI"},
	{"v0", "v0 CLI"},
	{"cursor", "Cursor CLI"},
	{"windsurf", "Windsurf CLI"},
}

// detectAgents checks which known agent binaries are in PATH.
// Returns the subset of knownAgents that were found.
func detectAgents() []knownAgent {
	var found []knownAgent
	for _, a := range knownAgents {
		if _, err := exec.LookPath(a.Binary); err == nil {
			found = append(found, a)
		}
	}
	return found
}

// generateEnvSh builds the content of ~/.quint/env.sh with CA trust vars
// and shell function wrappers for detected AI agent CLIs.
func generateEnvSh(bundlePath, certPath string, port int, agents []knownAgent) string {
	var b strings.Builder

	b.WriteString(`# Quint Agent Security — environment setup
# Generated by: quint setup
# Re-generate with: quint setup --env-only

# ── CA Trust (always active, harmless without proxy) ──────────
`)
	fmt.Fprintf(&b, "export SSL_CERT_FILE=%s\n", bundlePath)
	fmt.Fprintf(&b, "export NODE_EXTRA_CA_CERTS=%s\n", certPath)
	b.WriteString("export NODE_USE_SYSTEM_CA=1\n")

	if len(agents) == 0 {
		b.WriteString("\n# No AI agent CLIs detected in PATH during setup.\n")
		b.WriteString("# Install an agent (e.g. claude, codex, aider) then run: sudo quint setup --env-only\n")
		return b.String()
	}

	b.WriteString(`
# ── Agent Proxy Wrappers ─────────────────────────────────────
# These route AI agent CLI traffic through the Quint proxy.
# Other commands (npm, git, brew, curl) are unaffected.
# GUI apps are routed via the macOS system PAC file.
_quint_proxy() {
  if command -v nc >/dev/null 2>&1 && nc -z 127.0.0.1 `)
	fmt.Fprintf(&b, "%d", port)
	b.WriteString(` 2>/dev/null; then
    HTTP_PROXY="http://127.0.0.1:`)
	fmt.Fprintf(&b, "%d", port)
	b.WriteString(`" \
    HTTPS_PROXY="http://127.0.0.1:`)
	fmt.Fprintf(&b, "%d", port)
	b.WriteString(`" \
    "$@"
  else
    "$@"
  fi
}

`)

	// Write wrapper functions for each detected agent
	for _, a := range agents {
		fmt.Fprintf(&b, "%s() { _quint_proxy command %s \"$@\"; }  # %s\n", a.Binary, a.Binary, a.Name)
	}

	return b.String()
}

// generateEnvFish builds the content of ~/.quint/env.fish with CA trust vars
// and fish shell function wrappers for detected AI agent CLIs.
func generateEnvFish(bundlePath, certPath string, port int, agents []knownAgent) string {
	var b strings.Builder

	b.WriteString(`# Quint Agent Security — fish shell config
# Generated by: quint setup
# Re-generate with: quint setup --env-only

# ── CA Trust (always active, harmless without proxy) ──────────
`)
	fmt.Fprintf(&b, "set -gx SSL_CERT_FILE %s\n", bundlePath)
	fmt.Fprintf(&b, "set -gx NODE_EXTRA_CA_CERTS %s\n", certPath)
	b.WriteString("set -gx NODE_USE_SYSTEM_CA 1\n")

	if len(agents) == 0 {
		b.WriteString("\n# No AI agent CLIs detected in PATH during setup.\n")
		b.WriteString("# Install an agent (e.g. claude, codex, aider) then run: quint setup --env-only\n")
		return b.String()
	}

	b.WriteString(`
# ── Agent Proxy Wrappers ─────────────────────────────────────
# These route AI agent CLI traffic through the Quint proxy.
# Other commands (npm, git, brew, curl) are unaffected.
# GUI apps are routed via the macOS system PAC file.
function _quint_proxy
    if command -q nc; and nc -z 127.0.0.1 `)
	fmt.Fprintf(&b, "%d", port)
	b.WriteString(` 2>/dev/null
        set -lx HTTP_PROXY "http://127.0.0.1:`)
	fmt.Fprintf(&b, "%d", port)
	b.WriteString(`"
        set -lx HTTPS_PROXY "http://127.0.0.1:`)
	fmt.Fprintf(&b, "%d", port)
	b.WriteString(`"
        command $argv
    else
        command $argv
    end
end

`)

	// Write wrapper functions for each detected agent
	for _, a := range agents {
		fmt.Fprintf(&b, "function %s; _quint_proxy %s $argv; end  # %s\n", a.Binary, a.Binary, a.Name)
	}

	return b.String()
}

// hasFishConfig returns true if the user has a fish shell config directory.
func hasFishConfig(home string) bool {
	fishConfig := filepath.Join(home, ".config", "fish", "config.fish")
	_, err := os.Stat(fishConfig)
	return err == nil
}
